# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: wgyt website
    url: https://www.wgyt.tk
  - name: wgyt api
    url: https://api.wgyt.tk
  - name: wgyt auth
    url: https://auth.wgyt.tk
  - name: wgyt bot
    url: https://bot.wgyt.tk
  - name: wgyt chat
    url: https://chat.wgyt.tk
  - name: wgyt comments
    url: https://comments.wgyt.tk
  - name: wgyt documentation
    url: https://documentation.wgyt.tk
  - name: wgyt.cf
    url: https://wgyt.cf
  - name: wgyt on grahamsh.com
    url: https://wgyt.grahamsh.com


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.wgyt.tk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars2.githubusercontent.com/u/68466727?s=60&v=4
  name: Wgyt | Status
  introTitle: "Wgyt | Status is the status page for all of @wgyt's websites"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/wgytwebsites/stats.wgyt.tk). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
