owner: wgytwebsites
repo: stats.wgyt.tk

sites:
  - name: api.wgyt.tk
    url: https://api.wgyt.tk/about
  - name: auth.wgyt.tk
    url: https://auth.wgyt.tk/
  - name: josh bot (bot.wgyt.tk)
    url: https://bot.wgyt.tk/
  - name: documentation.wgyt.tk
    url: https://documentation.wgyt.tk/
  - name: social.wgyt.tk
    url: https://social.wgyt.tk/
  - name: stats.wgyt.tk (it is up lol)
    url: https://stats.wgyt.tk/
  - name: wgytcraft.cf
    url: https://wgytcraft.cf/
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 501
  - name: wgyt.tk
    url: https://auth.wgyt.tk/
  - name: wgyt.grahamsh.com
    url: https://wgyt.grahamsh.com/
  - name: wgyt.cf
    url: https://auth.wgyt.tk/
  - name: simpleedit.tk
    url: https://simpleedit.tk/
  - name: meower.tk
    url: https://meower.tk/
  - name: meowerplus.tk
    url: https://meowerplus.tk/
  - name: mastermindstudio.tk
    url: https://mastermindstudio.tk/
  - name: grocerycheck.ga
    url: https://grocerycheck.ga/
  - name: galacticaos.tk
    url: https://galacticaos.tk/
  - name: galaxydesign.ga
    url: https://galaxydesign.ga/

assignees:
  - wgyt

status-website:
  themeUrl: https://stats.wgyt.tk/themes/custom.css
  name: Wgyt Status
  logoUrl: https://www.wgyt.tk/images/logo.webp
  cname: stats.wgyt.tk # Custom CNAME
  navbar:
    - title: Wgyt Status
      href: /
  
